### ISSUE TITLE
`PrintPlayer()` is hardcoded to output to the terminal

### ISSUE THREAD

**Issue by Rosuavio** [CholiCub/A-Journey-For-Love#2]
The `Player` class is almost a really good domain object (object in the domain driven design sense), but its tired directly to the application console with `PrintPlayer()`. There should be a few ways to separate out the actual "printing to the console" from the "formatting for readability" code, so that the chose to print to console can happen outside of `Player`.

Some thoughts,
1. The function and return a formatted string and leave the rest to the caller.
2. The function can take a [ostream](https://cplusplus.com/reference/ostream/ostream/) and write to it rather than `cout`.
3. Probably similar to number 2, you might be able to overload the `<<` operator?

**Comment by CholiCub** [comment]
Overloaded the << operator for Player class 67c9d53
